In [40]:
import pandas as pd
import seaborn as sns
import numpy as np
import os

In [41]:
%matplotlib inline

In [42]:
repos_path = "/Users/Clayton/temporal-features-for-buildings/"

In [43]:
meta = pd.read_csv(os.path.join(repos_path,"data/raw/meta_open.csv"), index_col='uid', parse_dates=["datastart","dataend"], dayfirst=True)

In [44]:
temp = pd.read_csv((os.path.join(repos_path,"data/interim/temp_open_utc_complete.csv")), index_col='timestamp', parse_dates=True).tz_localize('utc')

In [45]:
meta

,dataend,datastart,energystarscore,heatingtype,industry,mainheatingtype,numberoffloors,occupants,primaryspaceusage,rating,sqft,sqm,subindustry,timezone,yearbuilt,nickname,primaryspaceuse_abbrev,newweatherfilename
uid,,,,,,,,,,,,,,,,,,
PrimClass_Everett,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,105530.00000,9804.053590,Primary/Secondary School,America/New_York,NaN,Everett,PrimClass,weather12.csv
UnivClass_Clifford,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Classroom,NaN,56969.00000,5292.591007,College/University,America/New_York,1967,Clifford,UnivClass,weather2.csv
Office_Elizabeth,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Commercial Property,NaN,NaN,NaN,Office,NaN,294651.00000,27373.961850,Commercial Real Estate,America/Los_Angeles,NaN,Elizabeth,Office,weather22.csv
Office_Ellie,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Commercial Property,NaN,NaN,NaN,Office,NaN,496517.00000,46127.918850,Bank/Financial Services,America/Los_Angeles,NaN,Ellie,Office,weather28.csv
PrimClass_Elisabeth,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,233062.00000,21652.158990,Primary/Secondary School,America/New_York,NaN,Elisabeth,PrimClass,weather23.csv
Office_Cristina,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,92271.00000,8572.252713,College/University,America/New_York,2001,Cristina,Office,weather2.csv
PrimClass_Jolie,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Education,Gas,2.0,212.0,Primary/Secondary Classroom,C,31505.93530,2927.000000,Primary/Secondary School,Europe/London,pre 1919,Jolie,PrimClass,weather1.csv
PrimClass_Jaylin,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Education,Gas,2.0,219.0,Primary/Secondary Classroom,C,47070.53470,4373.000000,Primary/Secondary School,Europe/London,1919-1945,Jaylin,PrimClass,weather1.csv
Office_Jesus,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Government,Gas,1.0,40.0,Office,C,42646.57180,3962.000000,"City, County, State",Europe/London,Post 1976,Jesus,Office,weather1.csv
PrimClass_Esmeralda,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,276443.00000,25682.384030,Primary/Secondary School,America/New_York,NaN,Esmeralda,PrimClass,weather17.csv
PrimClass_Eoghan,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,315404.00000,29301.977810,Primary/Secondary School,America/New_York,NaN,Eoghan,PrimClass,weather14.csv
PrimClass_Edwin,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,77247.00000,7176.478041,Primary/Secondary School,America/Denver,NaN,Edwin,PrimClass,weather35.csv
PrimClass_Eli,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,108405.00000,10071.149720,Primary/Secondary School,America/New_York,NaN,Eli,PrimClass,weather12.csv
PrimClass_Ethel,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,92032.00000,8550.048896,Primary/Secondary School,America/Denver,NaN,Ethel,PrimClass,weather18.csv
PrimClass_Ernesto,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,72333.00000,6719.952699,Primary/Secondary School,America/Denver,NaN,Ernesto,PrimClass,weather18.csv
PrimClass_Emanuela,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,95132.00000,8838.048196,Primary/Secondary School,America/Chicago,NaN,Emanuela,PrimClass,weather26.csv
PrimClass_Emilio,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,105215.00000,9774.789145,Primary/Secondary School,America/New_York,NaN,Emilio,PrimClass,weather12.csv
PrimClass_Eleanor,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,81681.00000,7588.409943,Primary/Secondary School,America/New_York,NaN,Eleanor,PrimClass,weather24.csv
PrimClass_Ezekiel,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,153699.00000,14279.098200,Primary/Secondary School,America/New_York,NaN,Ezekiel,PrimClass,weather29.csv
PrimClass_Elliott,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,217241.00000,20182.340620,Primary/Secondary School,America/New_York,NaN,Elliott,PrimClass,weather15.csv
PrimClass_Ellen,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,79503.00000,7386.067209,Primary/Secondary School,America/Chicago,NaN,Ellen,PrimClass,weather19.csv
PrimClass_Evie,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,197266.00000,18326.603200,Primary/Secondary School,America/Chicago,NaN,Evie,PrimClass,weather11.csv
PrimClass_Elijah,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,94150.00000,8746.817450,Primary/Secondary School,America/New_York,NaN,Elijah,PrimClass,weather14.csv
PrimClass_Ezra,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,92179.00000,8563.705637,Primary/Secondary School,America/New_York,NaN,Ezra,PrimClass,weather17.csv
PrimClass_Edmund,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,86867.00000,8070.204901,Primary/Secondary School,America/New_York,NaN,Edmund,PrimClass,weather15.csv
PrimClass_Eva,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,132737.00000,12331.665510,Primary/Secondary School,America/New_York,NaN,Eva,PrimClass,weather15.csv
Office_Erik,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Commercial Property,NaN,NaN,NaN,Office,NaN,126205.00000,11724.823120,Business Services,America/New_York,NaN,Erik,Office,weather14.csv
PrimClass_Ebony,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,175537.00000,16307.913910,Primary/Secondary School,America/Chicago,NaN,Ebony,PrimClass,weather11.csv
PrimClass_Ethan,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,80224.00000,7453.050272,Primary/Secondary School,America/New_York,NaN,Ethan,PrimClass,weather38.csv
PrimClass_Elmer,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,97901.00000,9095.296603,Primary/Secondary School,America/Chicago,NaN,Elmer,PrimClass,weather11.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UnivLab_Cristian,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,214505.00000,19928.158020,College/University,America/New_York,1990,Cristian,UnivLab,weather2.csv
UnivLab_Carley,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,56497.00000,5248.740791,College/University,America/New_York,1957,Carley,UnivLab,weather2.csv
UnivLab_Alina,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,49662.00000,4613.748786,College/University,America/Phoenix,1964,Alina,UnivLab,weather0.csv
UnivLab_Allison,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,4689.00000,435.622167,College/University,America/Phoenix,2005,Allison,UnivLab,weather0.csv
UnivLab_Peyton,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,250000.00000,23225.750000,College/University,America/New_York,NaN,Peyton,UnivLab,weather4.csv
Office_Marcia,2015-04-30 23:00:00,2014-05-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,62837.00000,5837.745811,College/University,America/Chicago,NaN,Marcia,Office,weather3.csv
UnivLab_Aine,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,48411.00000,4497.527133,College/University,America/Phoenix,NaN,Aine,UnivLab,weather0.csv
UnivLab_Santiago,2015-11-30 23:00:00,2014-12-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,G,107585.18050,9995.000000,College/University,Europe/London,2010,Santiago,UnivLab,weather6.csv
UnivLab_Anita,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,151637.00000,14087.532210,College/University,America/Phoenix,1983,Anita,UnivLab,weather0.csv
UnivLab_Parker,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,46813.00000,4349.068139,College/University,America/New_York,NaN,Parker,UnivLab,weather4.csv
UnivLab_Lee,2015-11-30 23:00:00,2014-12-01,NaN,Oil,Education,Oil,5.0,NaN,College Laboratory,NaN,37264.62180,3462.000000,College/University,Europe/London,1800,Lee,UnivLab,weather33.csv
Office_Dorian,2010-12-31 23:00:00,2010-01-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,111077.00000,10319.386530,College/University,America/Los_Angeles,1994,Dorian,Office,weather13.csv
Office_Shelly,2015-11-30 23:00:00,2014-12-01,NaN,NaN,Education,NaN,NaN,NaN,Office,C,15812.16910,1469.000000,College/University,Europe/London,NaN,Shelly,Office,weather6.csv
UnivLab_Alisa,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,193294.00000,17957.592480,College/University,America/Phoenix,2006,Alisa,UnivLab,weather0.csv
UnivLab_Louie,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Education,Gas,5.0,NaN,College Laboratory,G,21538.56390,2001.000000,College/University,Europe/London,2004,Louie,UnivLab,weather5.csv
UnivLab_Priscilla,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,35990.00000,3343.578970,College/University,America/New_York,NaN,Priscilla,UnivLab,weather4.csv
UnivLab_Patrick,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,75929.00000,7054.031887,College/University,America/New_York,NaN,Patrick,UnivLab,weather4.csv
UnivDorm_Adriana,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,Dormitory,NaN,63348.00000,5885.219244,College/University,America/Phoenix,2007,Adriana,UnivDorm,weather0.csv
UnivLab_Carole,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,149762.00000,13913.339090,College/University,America/New_York,2004,Carole,UnivLab,weather2.csv
UnivLab_Paris,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,120836.00000,11226.026910,College/University,America/New_York,NaN,Paris,UnivLab,weather4.csv
Office_Pauline,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,41337.00000,3840.331311,College/University,America/New_York,NaN,Pauline,Office,weather4.csv
UnivLab_Dianna,2010-12-31 23:00:00,2010-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,153700.00000,14279.191100,College/University,America/Los_Angeles,1990,Dianna,UnivLab,weather13.csv
UnivDorm_Cecilia,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,Dormitory,NaN,29775.00000,2766.186825,College/University,America/New_York,2001,Cecilia,UnivDorm,weather2.csv
Office_Luann,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Education,Gas,8.0,NaN,Office,E,65656.56083,6099.700000,College/University,Europe/London,1955,Luann,Office,weather5.csv
Office_Milton,2015-04-30 23:00:00,2014-05-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,105167.00000,9770.329801,College/University,America/Chicago,NaN,Milton,Office,weather3.csv
Office_Lane,2015-11-30 23:00:00,2014-12-01,NaN,Heat network,Education,Heat Network,8.0,NaN,Office,NaN,34455.24390,3201.000000,College/University,Europe/London,1907,Lane,Office,weather5.csv
Office_Cameron,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,53303.00000,4952.008609,College/University,America/New_York,1981,Cameron,Office,weather2.csv
UnivLab_Lea,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Education,Gas,6.0,NaN,College Laboratory,NaN,16802.44790,1561.000000,College/University,Europe/London,1995,Lea,UnivLab,weather5.csv
UnivLab_Carlos,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,30143.00000,2800.375129,College/University,America/New_York,1951,Carlos,UnivLab,weather2.csv
UnivLab_Aoife,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,261188.00000,24265.148760,College/University,America/Phoenix,NaN,Aoife,UnivLab,weather0.csv

In [46]:
meta_tooutput = meta[['primaryspaceuse_abbrev']]

In [47]:
meta_tooutput['outputfile'] = meta_tooutput.index+".dat"

/Users/Clayton/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [48]:
meta_tooutput.index = meta_tooutput.outputfile

In [49]:
meta_tooutput.head()

                        primaryspaceuse_abbrev               outputfile
outputfile
PrimClass_Everett.dat                PrimClass    PrimClass_Everett.dat
UnivClass_Clifford.dat               UnivClass   UnivClass_Clifford.dat
Office_Elizabeth.dat                    Office     Office_Elizabeth.dat
Office_Ellie.dat                        Office         Office_Ellie.dat
PrimClass_Elisabeth.dat              PrimClass  PrimClass_Elisabeth.dat

In [50]:
meta_tooutput = meta_tooutput['primaryspaceuse_abbrev']

In [34]:
meta_tooutput.to_csv("/Users/Clayton/hctsa/TimeSeries//INP_buildinggenome.txt",sep=" ", header=False)

Make temp files

In [35]:
buildinglist = list(meta.index)

In [39]:
for buildingname in buildinglist:
    print buildingname
    temp[buildingname].dropna().to_csv("/Users/Clayton/hctsa/TimeSeries/"+buildingname+".dat",header=False, index=False)

PrimClass_Everett
UnivClass_Clifford
Office_Elizabeth
Office_Ellie
PrimClass_Elisabeth
Office_Cristina
PrimClass_Jolie
PrimClass_Jaylin
Office_Jesus
PrimClass_Esmeralda
PrimClass_Eoghan
PrimClass_Edwin
PrimClass_Eli
PrimClass_Ethel
PrimClass_Ernesto
PrimClass_Emanuela
PrimClass_Emilio
PrimClass_Eleanor
PrimClass_Ezekiel
PrimClass_Elliott
PrimClass_Ellen
PrimClass_Evie
PrimClass_Elijah
PrimClass_Ezra
PrimClass_Edmund
PrimClass_Eva
Office_Erik
PrimClass_Ebony
PrimClass_Ethan
PrimClass_Elmer
PrimClass_Ervin
PrimClass_Uma
UnivClass_Tamra
PrimClass_Ernest
PrimClass_Emily
Office_Evelyn
PrimClass_Jayla
Office_Emer
PrimClass_Janiya
PrimClass_Umar
Office_Elena
PrimClass_Janice
Office_Jett
UnivDorm_Una
UnivLab_Paul
Office_Jerry
Office_Eileen
PrimClass_Uriah
PrimClass_Ulysses
Office_Lesa
UnivDorm_Claudia
Office_Emerald
Office_Ellis
UnivClass_Tammy
PrimClass_Jaden
Office_Elliot
PrimClass_Jermaine
PrimClass_Josephine
Office_Eddie
Office_Jackie
UnivDorm_Carla
UnivClass_Camden
PrimClass_Javier
PrimClass_Jeanette
PrimClass_Julius
PrimClass_Jaylinn
PrimClass_Johanna
PrimClass_Jodie
PrimClass_Johnathan
PrimClass_Janis
PrimClass_Jamal
PrimClass_Jose
PrimClass_Julianna
PrimClass_Jasmine
PrimClass_Jazmine
PrimClass_Justin
Office_Marla
PrimClass_Jody
PrimClass_Julianne
PrimClass_Justice
UnivClass_Craig
PrimClass_Jean
PrimClass_Jenna
PrimClass_Judith
PrimClass_Jessie
PrimClass_Joselyn
UnivLab_Bethany
PrimClass_Judy
PrimClass_Jarrett
PrimClass_Jeannine
PrimClass_Jeff
PrimClass_Julian
PrimClass_Jeanine
UnivClass_Jadon
Office_Maryann
UnivClass_Boyd
PrimClass_Jerome
PrimClass_Jacqueline
PrimClass_Jill
PrimClass_Jim
Office_Myron
PrimClass_Janet
PrimClass_Janie
PrimClass_Jensen
PrimClass_Jeffrey
Office_Conrad
UnivDorm_Prince
PrimClass_Jennifer
UnivClass_Therese
PrimClass_Jesse
Office_Mick
PrimClass_Jaxson
PrimClass_Jimmie
Office_Jayden
UnivDorm_Chelsey
PrimClass_Jayda
UnivDorm_Christopher
PrimClass_Jocelyn
PrimClass_Jeffery
UnivDorm_Cheyenne
UnivDorm_Patti
PrimClass_Jayson
UnivLab_Crystal
UnivDorm_Jeannette
Office_Moises
PrimClass_Jennie
PrimClass_Jonathon
UnivDorm_Christi
PrimClass_Jaqueline
UnivClass_Amari
Office_Tod
PrimClass_Jeremy
PrimClass_Josue
UnivDorm_Marlene
UnivClass_Teri
PrimClass_Julio
UnivDorm_Cheri
UnivDorm_Lorraine
PrimClass_Jacquelyn
PrimClass_Juanita
PrimClass_Joel
Office_Marcus
UnivClass_Candy
PrimClass_Joey
UnivDorm_Celeste
UnivClass_Shawna
PrimClass_Joanna
UnivClass_Ariana
PrimClass_Jediah
Office_Bobbi
Office_Georgia
PrimClass_Janelle
Office_Skyler
Office_Marc
Office_Mary
UnivDorm_Payton
Office_Ayesha
PrimClass_Jane
PrimClass_Jon
UnivDorm_Patty
UnivDorm_Adan
Office_Monty
UnivLab_Clint
PrimClass_Jake
Office_Joan
UnivLab_Cesar
UnivDorm_Cian
PrimClass_Johnnie
Office_Marlon
UnivDorm_Curtis
UnivDorm_Leonard
Office_Javon
UnivClass_Pete
PrimClass_Johnathon
Office_Jeanne
PrimClass_Jamie
Office_Pamela
Office_Allyson
PrimClass_Jacob
Office_Amelie
UnivDorm_Patrice
UnivClass_Alexander
Office_Maximus
Office_Ava
Office_Michael
Office_Caleb
Office_Scottie
Office_Cecelia
Office_Nelson
PrimClass_Angela
Office_Abbey
UnivDorm_Candace
UnivDorm_Clayton
UnivDorm_Ahmad
UnivClass_Armando
UnivDorm_April
Office_John
Office_Moses
UnivDorm_Corey
Office_Martha
UnivClass_Anamaria
UnivDorm_Cooper
UnivClass_Andy
UnivClass_Archie
Office_Mercedes
UnivClass_Stuart
Office_Mat
Office_Clifton
UnivLab_Cindy
UnivLab_Neil
Office_Marilyn
UnivDorm_Malachi
UnivDorm_Mathew
UnivDorm_Ashleigh
Office_Malik
UnivClass_Sam
UnivClass_Alec
UnivClass_Alvin
Office_Alyson
Office_Benjamin
UnivDorm_Piper
UnivDorm_Colton
UnivDorm_Paola
UnivLab_Miles
UnivDorm_Lawrence
UnivClass_Sheila
UnivDorm_Alonzo
UnivClass_Beatrice
Office_Mohammed
UnivDorm_Chester
UnivLab_Tami
Office_Bianca
UnivDorm_Phillip
UnivDorm_Mitch
UnivDorm_Casey
UnivClass_Colette
Office_Benthe
Office_Gemma
UnivDorm_Leticia
Office_Micheal
UnivClass_Abraham
UnivDorm_Leslie
UnivDorm_Poppy
Office_Corbin
Office_Aubrey
Office_Autumn
Office_Abigail
Office_Mark
UnivDorm_Lysander
UnivClass_Christian
UnivClass_Alexandra
UnivLab_Tracie
UnivClass_Philip
UnivDorm_Antonio
UnivDorm_Malcolm
Office_Travis
Office_Lena
Office_Max
UnivClass_Allen
UnivDorm_Ciaran
UnivClass_Pandora
Office_Gustavo
UnivDorm_Alyssa
UnivClass_Axel
UnivDorm_Phoebe
Office_Penny
Office_Garrett
UnivLab_Terrie
UnivLab_Tracy
UnivClass_Phyllis
UnivDorm_Marquis
PrimClass_Jazmin
UnivClass_Seb
Office_Annika
Office_Shawnette
Office_Cody
PrimClass_Jaiden
Office_Charles
UnivDorm_Avery
UnivLab_Taylor
UnivClass_Carl
Office_Pam
UnivClass_Conor
UnivLab_Lilly
UnivDorm_Mauricio
UnivClass_Maddison
UnivClass_Annmarie
Office_Asher
UnivDorm_Petar
UnivClass_Stephen
UnivClass_Serenity
Office_Mada
Office_Lillian
Office_Al
UnivLab_Preston
Office_Clarissa
UnivClass_Nishka
Office_Andrea
UnivDorm_Mckenzie
UnivClass_Ayanna
UnivClass_Nickolas
UnivClass_Amya
UnivClass_Nathaniel
UnivDorm_Alka
Office_Pat
UnivClass_Charlie
UnivLab_Alexis
UnivClass_Alexandria
UnivClass_Annabella
UnivClass_Antoinette
UnivDorm_Cathal
Office_Marianne
UnivLab_Cedric
Office_Angelo
Office_Anastasia
Office_Marvin
Office_Glenda
UnivClass_Sylvia
UnivLab_Susan
UnivClass_Peter
UnivClass_Aoibhe
UnivClass_Ciara
Office_Brian
UnivLab_Beth
UnivClass_Anya
Office_Maya
Office_Gisselle
Office_Phebian
Office_Matthew
UnivClass_Bob
Office_Amelia
Office_Jan
UnivClass_Alicia
Office_Madeleine
Office_Angelina
Office_Jackson
Office_Melinda
Office_Catherine
UnivDorm_Carter
Office_Gloria
UnivClass_Alexus
UnivDorm_Leann
UnivClass_Anne
UnivDorm_Cornelius
Office_Sinead
Office_Megan
UnivClass_Alfredo
UnivClass_Conner
UnivClass_Nelly
UnivDorm_Alex
Office_Shari
Office_Madisyn
Office_Natasha
UnivClass_Calvin
Office_Jude
UnivLab_Aniya
UnivDorm_Alphonso
Office_Angelica
Office_Morgan
UnivLab_Adrian
UnivLab_Christy
Office_Marion
UnivLab_Christine
UnivDorm_Cara
UnivClass_Adrienne
UnivClass_Nicholas
UnivClass_Nayeli
UnivClass_Carolyn
Office_Joni
UnivLab_Madelyn
UnivLab_Arianna
UnivLab_Ciel
Office_Paige
Office_Martin
UnivClass_Clay
PrimClass_Angel
Office_Muhammad
UnivLab_Ali
Office_Gladys
Office_Stella
UnivLab_Brad
Office_Louise
UnivClass_Noreen
UnivLab_Mack
UnivLab_Mariana
Office_Guillermo
Office_Paulina
UnivLab_Cayden
Office_Gabriela
UnivDorm_Pedro
UnivLab_Albert
UnivLab_Alaina
UnivLab_Ana
UnivDorm_Constance
Office_Carolina
UnivDorm_Cathalina
Office_Noel
UnivClass_Anika
UnivLab_Clodagh
UnivLab_Annette
Office_Alannah
Office_Aliyah
Office_Curt
UnivDorm_Carey
UnivLab_Angie
UnivClass_Celia
Office_Glenn
UnivLab_Andre
Office_Terrell
UnivDorm_Laura
UnivLab_Mario
UnivClass_Aidan
UnivLab_Annabelle
Office_Leland
UnivClass_Brett
UnivLab_Caesar
Office_Mikayla
UnivClass_Stephanie
UnivLab_Marshall
Office_Ayden
UnivClass_Cathleen
UnivLab_Collin
UnivDorm_Camila
UnivClass_Alejandra
Office_Colby
Office_Carissa
UnivLab_Peggy
Office_Paula
UnivLab_Marie
UnivLab_Suzette
UnivLab_Alberto
UnivLab_Aurora
UnivLab_Lyle
UnivLab_Lauren
UnivLab_Ariel
Office_Ashanti
UnivClass_Caoimhe
UnivLab_Cam
Office_Garman
UnivLab_Phil
Office_Cora
UnivLab_Ashlee
UnivClass_Nash
UnivLab_Allan
UnivLab_Bert
UnivClass_Chandler
UnivLab_Callie
UnivLab_Caitlin
UnivLab_Ashlynn
Office_Mason
UnivLab_Alfonso
UnivDorm_Alyshialynn
UnivLab_Amaya
UnivLab_Carol
Office_Clinton
UnivLab_Ashton
UnivLab_Cory
UnivLab_Cheyanne
Office_Paulette
UnivLab_Amy
Office_Dawn
Office_Perla
Office_Precious
Office_Patricia
UnivLab_Carlton
UnivLab_Camryn
UnivLab_Margret
UnivLab_Cecil
Office_Pasquale
UnivLab_Levi
UnivLab_Patsy
Office_Bryon
UnivClass_Abby
UnivLab_Brenna
UnivLab_Audra
UnivLab_Lester
UnivClass_Caitlyn
UnivLab_Cristian
UnivLab_Carley
UnivLab_Alina
UnivLab_Allison
UnivLab_Peyton
Office_Marcia
UnivLab_Aine
UnivLab_Santiago
UnivLab_Anita
UnivLab_Parker
UnivLab_Lee
Office_Dorian
Office_Shelly
UnivLab_Alisa
UnivLab_Louie
UnivLab_Priscilla
UnivLab_Patrick
UnivDorm_Adriana
UnivLab_Carole
UnivLab_Paris
Office_Pauline
UnivLab_Dianna
UnivDorm_Cecilia
Office_Luann
Office_Milton
Office_Lane
Office_Cameron
UnivLab_Lea
UnivLab_Carlos
UnivLab_Aoife

# Make files that are similar to the output files from the hctsa to create the same visualizations

In [196]:
features = pd.read_csv(os.path.join(repos_path, "data/processed/ALLFEATURES.CSV"), index_col="Unnamed: 0")

In [197]:
features.info()

<class 'pandas.core.frame.DataFrame'>
Index: 507 entries, Office_Abbey to UnivLab_Tracy
Columns: 166 entries, BG_breakouts_max: to BG_visdom_t90t
dtypes: float64(166)
memory usage: 661.5+ KB

In [198]:
features.columns

Index([u'BG_breakouts_max:', u'BG_dayfilterfreq_mean', u'BG_dayfilterfreq_std',
       u'BG_dayfilterfreq_min', u'BG_dayfilterfreq_max',
       u'BG_eemeter_cooling_mean', u'BG_eemeter_cooling_std',
       u'BG_eemeter_cooling_min', u'BG_eemeter_cooling_max',
       u'BG_eemeter_heating_mean',
       ...
       u'BG_visdom_min.hr.kw', u'BG_visdom_min.hr.tout', u'BG_visdom_mn2mx',
       u'BG_visdom_n2d', u'BG_visdom_nv2dv', u'BG_visdom_range',
       u'BG_visdom_t10kw', u'BG_visdom_t10t', u'BG_visdom_t90kw',
       u'BG_visdom_t90t'],
      dtype='object', length=166)

In [225]:
operations = pd.DataFrame(features.columns)

In [240]:
operations = pd.DataFrame(operations.str.replace('[^\w\s]',''))

In [241]:
operations

                                 0
0                 BG_breakouts_max
1            BG_dayfilterfreq_mean
2             BG_dayfilterfreq_std
3             BG_dayfilterfreq_min
4             BG_dayfilterfreq_max
5          BG_eemeter_cooling_mean
6           BG_eemeter_cooling_std
7           BG_eemeter_cooling_min
8           BG_eemeter_cooling_max
9          BG_eemeter_heating_mean
10          BG_eemeter_heating_std
11          BG_eemeter_heating_min
12          BG_eemeter_heating_max
13             BG_eemeter_baseload
14            BG_eemeter_heatbalpt
15            BG_eemeter_heatslope
16            BG_eemeter_coolbalpt
17            BG_eemeter_coolslope
18                 BG_eemeter_nmbe
19               BG_eemeter_cvrmse
20   BG_jmotif_inclasssim_168_6_14
21       BG_weeklyspecificity_mean
22        BG_weeklyspecificity_std
23        BG_weeklyspecificity_min
24        BG_weeklyspecificity_max
25     BG_jmotif_inclasssim_24_8_8
26      BG_weeklyspecificity_mean1
27       BG_weeklyspecificity_std1
28       BG_weeklyspecificity_min1
29       BG_weeklyspecificity_max1
..                             ...
136                 BG_visdom_kw90
137        BG_visdom_BG_visdom_max
138                BG_visdom_max97
139                BG_visdom_maxMA
140           BG_visdom_maxdaydate
141             BG_visdom_maxdaykw
142  BG_visdom_BG_visdom_maxdaypct
143           BG_visdom_maxdaytout
144            BG_visdom_maxhrdate
145              BG_visdom_maxhrkw
146            BG_visdom_maxhrtout
147               BG_visdom_maxHOD
148                 BG_visdom_mean
149                  BG_visdom_min
150                 BG_visdom_min3
151           BG_visdom_mindaydate
152             BG_visdom_mindaykw
153            BG_visdom_mindaypct
154           BG_visdom_mindaytout
155            BG_visdom_minhrdate
156              BG_visdom_minhrkw
157            BG_visdom_minhrtout
158                BG_visdom_mn2mx
159                  BG_visdom_n2d
160                BG_visdom_nv2dv
161                BG_visdom_range
162                BG_visdom_t10kw
163                 BG_visdom_t10t
164                BG_visdom_t90kw
165                 BG_visdom_t90t

[166 rows x 1 columns]

In [242]:
operations['name'] = operations[0]
#operations['keywords'] = "misc,raw,lengthdep"

In [243]:
operations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 2 columns):
0       166 non-null object
name    166 non-null object
dtypes: object(2)
memory usage: 2.7+ KB

In [244]:
operations.to_csv("/Users/Clayton/hctsa/Database/INP_allbg_ops.txt", header=False, index=False, sep=" ")

In [245]:
#operations

In [246]:
masteroperations = operations

In [247]:
masteroperations = masteroperations.reset_index()

In [248]:
masteroperations[0] = masteroperations["index"].apply(lambda x: "AllBGOperations(y,"+str(x)+")")

In [249]:
#masteroperations

In [250]:
masteroperations = masteroperations.drop(['index'],axis=1)

In [253]:
masteroperations

                          0                           name
0      AllBGOperations(y,0)               BG_breakouts_max
1      AllBGOperations(y,1)          BG_dayfilterfreq_mean
2      AllBGOperations(y,2)           BG_dayfilterfreq_std
3      AllBGOperations(y,3)           BG_dayfilterfreq_min
4      AllBGOperations(y,4)           BG_dayfilterfreq_max
5      AllBGOperations(y,5)        BG_eemeter_cooling_mean
6      AllBGOperations(y,6)         BG_eemeter_cooling_std
7      AllBGOperations(y,7)         BG_eemeter_cooling_min
8      AllBGOperations(y,8)         BG_eemeter_cooling_max
9      AllBGOperations(y,9)        BG_eemeter_heating_mean
10    AllBGOperations(y,10)         BG_eemeter_heating_std
11    AllBGOperations(y,11)         BG_eemeter_heating_min
12    AllBGOperations(y,12)         BG_eemeter_heating_max
13    AllBGOperations(y,13)            BG_eemeter_baseload
14    AllBGOperations(y,14)           BG_eemeter_heatbalpt
15    AllBGOperations(y,15)           BG_eemeter_heatslope
16    AllBGOperations(y,16)           BG_eemeter_coolbalpt
17    AllBGOperations(y,17)           BG_eemeter_coolslope
18    AllBGOperations(y,18)                BG_eemeter_nmbe
19    AllBGOperations(y,19)              BG_eemeter_cvrmse
20    AllBGOperations(y,20)  BG_jmotif_inclasssim_168_6_14
21    AllBGOperations(y,21)      BG_weeklyspecificity_mean
22    AllBGOperations(y,22)       BG_weeklyspecificity_std
23    AllBGOperations(y,23)       BG_weeklyspecificity_min
24    AllBGOperations(y,24)       BG_weeklyspecificity_max
25    AllBGOperations(y,25)    BG_jmotif_inclasssim_24_8_8
26    AllBGOperations(y,26)     BG_weeklyspecificity_mean1
27    AllBGOperations(y,27)      BG_weeklyspecificity_std1
28    AllBGOperations(y,28)      BG_weeklyspecificity_min1
29    AllBGOperations(y,29)      BG_weeklyspecificity_max1
..                      ...                            ...
136  AllBGOperations(y,136)                 BG_visdom_kw90
137  AllBGOperations(y,137)        BG_visdom_BG_visdom_max
138  AllBGOperations(y,138)                BG_visdom_max97
139  AllBGOperations(y,139)                BG_visdom_maxMA
140  AllBGOperations(y,140)           BG_visdom_maxdaydate
141  AllBGOperations(y,141)             BG_visdom_maxdaykw
142  AllBGOperations(y,142)  BG_visdom_BG_visdom_maxdaypct
143  AllBGOperations(y,143)           BG_visdom_maxdaytout
144  AllBGOperations(y,144)            BG_visdom_maxhrdate
145  AllBGOperations(y,145)              BG_visdom_maxhrkw
146  AllBGOperations(y,146)            BG_visdom_maxhrtout
147  AllBGOperations(y,147)               BG_visdom_maxHOD
148  AllBGOperations(y,148)                 BG_visdom_mean
149  AllBGOperations(y,149)                  BG_visdom_min
150  AllBGOperations(y,150)                 BG_visdom_min3
151  AllBGOperations(y,151)           BG_visdom_mindaydate
152  AllBGOperations(y,152)             BG_visdom_mindaykw
153  AllBGOperations(y,153)            BG_visdom_mindaypct
154  AllBGOperations(y,154)           BG_visdom_mindaytout
155  AllBGOperations(y,155)            BG_visdom_minhrdate
156  AllBGOperations(y,156)              BG_visdom_minhrkw
157  AllBGOperations(y,157)            BG_visdom_minhrtout
158  AllBGOperations(y,158)                BG_visdom_mn2mx
159  AllBGOperations(y,159)                  BG_visdom_n2d
160  AllBGOperations(y,160)                BG_visdom_nv2dv
161  AllBGOperations(y,161)                BG_visdom_range
162  AllBGOperations(y,162)                BG_visdom_t10kw
163  AllBGOperations(y,163)                 BG_visdom_t10t
164  AllBGOperations(y,164)                BG_visdom_t90kw
165  AllBGOperations(y,165)                 BG_visdom_t90t

[166 rows x 2 columns]

In [252]:
masteroperations.to_csv("/Users/Clayton/hctsa/Database/INP_allbg_mops.txt", header=False, index=False, sep=" ")

In [256]:
TS_Quality = pd.DataFrame(0, index=np.arange(507), columns=np.arange(166))

In [257]:
TS_Quality

,0,1,2,3,4,5,6,7,8,9,...,156,157,158,159,160,161,162,163,164,165
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
478,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
479,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
480,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
481,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
482,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
483,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
484,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
485,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
486,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
487,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
488,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
491,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
492,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
493,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
494,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
495,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
501,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
502,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
503,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
504,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
505,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
506,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [258]:
TS_Quality.to_csv("/Users/Clayton/hctsa/TS_QualityDummy.txt", header=False, index=False)