# Creating input files for the hctsa using meta data

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import os

In [2]:
%matplotlib inline

In [3]:
repos_path = "/Users/Clayton/temporal-features-for-buildings/"

In [4]:
meta = pd.read_csv(os.path.join(repos_path,"data/raw/meta_open_withperformanceclasses.csv"), index_col='uid', parse_dates=["datastart","dataend"], dayfirst=True)

In [5]:
temp = pd.read_csv((os.path.join(repos_path,"data/interim/temp_open_utc_complete.csv")), index_col='timestamp', parse_dates=True).tz_localize('utc')

In [6]:
meta

,dataend,datastart,energystarscore,heatingtype,industry,mainheatingtype,numberoffloors,occupants,primaryspaceusage,rating,...,sqm,subindustry,timezone,yearbuilt,nickname,primaryspaceuse_abbrev,newweatherfilename,dailymeancons,usagecategory,operationsgroup
uid,,,,,,,,,,,,,,,,,,,,,
PrimClass_Everett,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,9804.053590,Primary/Secondary School,America/New_York,NaN,Everett,PrimClass,weather12.csv,0.005935,Low,Misc
UnivClass_Clifford,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Classroom,NaN,...,5292.591007,College/University,America/New_York,1967,Clifford,UnivClass,weather2.csv,0.006464,Low,Group3
Office_Elizabeth,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Commercial Property,NaN,NaN,NaN,Office,NaN,...,27373.961850,Commercial Real Estate,America/Los_Angeles,NaN,Elizabeth,Office,weather22.csv,0.007931,Low,Misc
Office_Ellie,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Commercial Property,NaN,NaN,NaN,Office,NaN,...,46127.918850,Bank/Financial Services,America/Los_Angeles,NaN,Ellie,Office,weather28.csv,0.008237,Low,Misc
PrimClass_Elisabeth,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,21652.158990,Primary/Secondary School,America/New_York,NaN,Elisabeth,PrimClass,weather23.csv,0.008597,Low,Misc
Office_Cristina,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,...,8572.252713,College/University,America/New_York,2001,Cristina,Office,weather2.csv,0.009302,Low,Group3
PrimClass_Jolie,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Education,Gas,2.0,212.0,Primary/Secondary Classroom,C,...,2927.000000,Primary/Secondary School,Europe/London,pre 1919,Jolie,PrimClass,weather1.csv,0.010486,Low,Group2
PrimClass_Jaylin,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Education,Gas,2.0,219.0,Primary/Secondary Classroom,C,...,4373.000000,Primary/Secondary School,Europe/London,1919-1945,Jaylin,PrimClass,weather1.csv,0.012248,Low,Group2
Office_Jesus,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Government,Gas,1.0,40.0,Office,C,...,3962.000000,"City, County, State",Europe/London,Post 1976,Jesus,Office,weather1.csv,0.011333,Low,Group2
PrimClass_Esmeralda,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,25682.384030,Primary/Secondary School,America/New_York,NaN,Esmeralda,PrimClass,weather17.csv,0.012033,Low,Misc
PrimClass_Eoghan,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,29301.977810,Primary/Secondary School,America/New_York,NaN,Eoghan,PrimClass,weather14.csv,0.012034,Low,Misc
PrimClass_Edwin,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,7176.478041,Primary/Secondary School,America/Denver,NaN,Edwin,PrimClass,weather35.csv,0.015420,Low,Misc
PrimClass_Eli,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,10071.149720,Primary/Secondary School,America/New_York,NaN,Eli,PrimClass,weather12.csv,0.016171,Low,Misc
PrimClass_Ethel,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,8550.048896,Primary/Secondary School,America/Denver,NaN,Ethel,PrimClass,weather18.csv,0.017022,Low,Misc
PrimClass_Ernesto,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,6719.952699,Primary/Secondary School,America/Denver,NaN,Ernesto,PrimClass,weather18.csv,0.017737,Low,Misc
PrimClass_Emanuela,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,8838.048196,Primary/Secondary School,America/Chicago,NaN,Emanuela,PrimClass,weather26.csv,0.018931,Low,Misc
PrimClass_Emilio,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,9774.789145,Primary/Secondary School,America/New_York,NaN,Emilio,PrimClass,weather12.csv,0.019014,Low,Misc
PrimClass_Eleanor,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,7588.409943,Primary/Secondary School,America/New_York,NaN,Eleanor,PrimClass,weather24.csv,0.019744,Low,Misc
PrimClass_Ezekiel,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,14279.098200,Primary/Secondary School,America/New_York,NaN,Ezekiel,PrimClass,weather29.csv,0.020990,Low,Misc
PrimClass_Elliott,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,20182.340620,Primary/Secondary School,America/New_York,NaN,Elliott,PrimClass,weather15.csv,0.021343,Low,Misc
PrimClass_Ellen,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,7386.067209,Primary/Secondary School,America/Chicago,NaN,Ellen,PrimClass,weather19.csv,0.021316,Low,Misc
PrimClass_Evie,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,18326.603200,Primary/Secondary School,America/Chicago,NaN,Evie,PrimClass,weather11.csv,0.021574,Low,Misc
PrimClass_Elijah,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,8746.817450,Primary/Secondary School,America/New_York,NaN,Elijah,PrimClass,weather14.csv,0.021603,Low,Misc
PrimClass_Ezra,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,8563.705637,Primary/Secondary School,America/New_York,NaN,Ezra,PrimClass,weather17.csv,0.021604,Low,Misc
PrimClass_Edmund,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,8070.204901,Primary/Secondary School,America/New_York,NaN,Edmund,PrimClass,weather15.csv,0.022317,Low,Misc
PrimClass_Eva,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,12331.665510,Primary/Secondary School,America/New_York,NaN,Eva,PrimClass,weather15.csv,0.022986,Low,Misc
Office_Erik,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Commercial Property,NaN,NaN,NaN,Office,NaN,...,11724.823120,Business Services,America/New_York,NaN,Erik,Office,weather14.csv,0.026642,Low,Misc
PrimClass_Ebony,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,16307.913910,Primary/Secondary School,America/Chicago,NaN,Ebony,PrimClass,weather11.csv,0.027169,Low,Misc
PrimClass_Ethan,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,7453.050272,Primary/Secondary School,America/New_York,NaN,Ethan,PrimClass,weather38.csv,0.029089,Low,Misc
PrimClass_Elmer,2012-12-31 23:00:00,2012-01-01,NaN,NaN,Education,NaN,NaN,NaN,Primary/Secondary Classroom,NaN,...,9095.296603,Primary/Secondary School,America/Chicago,NaN,Elmer,PrimClass,weather11.csv,0.029337,Low,Misc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
UnivLab_Cristian,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,19928.158020,College/University,America/New_York,1990,Cristian,UnivLab,weather2.csv,0.988298,High,Group3
UnivLab_Carley,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,5248.740791,College/University,America/New_York,1957,Carley,UnivLab,weather2.csv,0.999089,High,Group3
UnivLab_Alina,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,4613.748786,College/University,America/Phoenix,1964,Alina,UnivLab,weather0.csv,1.010131,High,Group1
UnivLab_Allison,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,435.622167,College/University,America/Phoenix,2005,Allison,UnivLab,weather0.csv,1.012501,High,Group1
UnivLab_Peyton,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,23225.750000,College/University,America/New_York,NaN,Peyton,UnivLab,weather4.csv,1.037661,High,Group5
Office_Marcia,2015-04-30 23:00:00,2014-05-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,...,5837.745811,College/University,America/Chicago,NaN,Marcia,Office,weather3.csv,1.017496,High,Group4
UnivLab_Aine,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,4497.527133,College/University,America/Phoenix,NaN,Aine,UnivLab,weather0.csv,1.056118,High,Group1
UnivLab_Santiago,2015-11-30 23:00:00,2014-12-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,G,...,9995.000000,College/University,Europe/London,2010,Santiago,UnivLab,weather6.csv,1.060934,High,Group7
UnivLab_Anita,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,14087.532210,College/University,America/Phoenix,1983,Anita,UnivLab,weather0.csv,1.116615,High,Group1
UnivLab_Parker,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,4349.068139,College/University,America/New_York,NaN,Parker,UnivLab,weather4.csv,1.159149,High,Group5
UnivLab_Lee,2015-11-30 23:00:00,2014-12-01,NaN,Oil,Education,Oil,5.0,NaN,College Laboratory,NaN,...,3462.000000,College/University,Europe/London,1800,Lee,UnivLab,weather33.csv,1.129811,High,Group6
Office_Dorian,2010-12-31 23:00:00,2010-01-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,...,10319.386530,College/University,America/Los_Angeles,1994,Dorian,Office,weather13.csv,1.154236,High,Group8
Office_Shelly,2015-11-30 23:00:00,2014-12-01,NaN,NaN,Education,NaN,NaN,NaN,Office,C,...,1469.000000,College/University,Europe/London,NaN,Shelly,Office,weather6.csv,1.188468,High,Group7
UnivLab_Alisa,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,17957.592480,College/University,America/Phoenix,2006,Alisa,UnivLab,weather0.csv,1.267327,High,Group1
UnivLab_Louie,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Education,Gas,5.0,NaN,College Laboratory,G,...,2001.000000,College/University,Europe/London,2004,Louie,UnivLab,weather5.csv,1.302863,High,Group6
UnivLab_Priscilla,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,3343.578970,College/University,America/New_York,NaN,Priscilla,UnivLab,weather4.csv,1.385840,High,Group5
UnivLab_Patrick,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,7054.031887,College/University,America/New_York,NaN,Patrick,UnivLab,weather4.csv,1.416430,High,Group5
UnivDorm_Adriana,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,Dormitory,NaN,...,5885.219244,College/University,America/Phoenix,2007,Adriana,UnivDorm,weather0.csv,1.395563,High,Group1
UnivLab_Carole,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,13913.339090,College/University,America/New_York,2004,Carole,UnivLab,weather2.csv,1.430881,High,Group3
UnivLab_Paris,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,11226.026910,College/University,America/New_York,NaN,Paris,UnivLab,weather4.csv,1.458855,High,Group5
Office_Pauline,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,...,3840.331311,College/University,America/New_York,NaN,Pauline,Office,weather4.csv,1.484026,High,Group5
UnivLab_Dianna,2010-12-31 23:00:00,2010-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,14279.191100,College/University,America/Los_Angeles,1990,Dianna,UnivLab,weather13.csv,1.565921,High,Group8
UnivDorm_Cecilia,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,Dormitory,NaN,...,2766.186825,College/University,America/New_York,2001,Cecilia,UnivDorm,weather2.csv,1.627664,High,Group3
Office_Luann,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Education,Gas,8.0,NaN,Office,E,...,6099.700000,College/University,Europe/London,1955,Luann,Office,weather5.csv,1.717340,High,Group6
Office_Milton,2015-04-30 23:00:00,2014-05-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,...,9770.329801,College/University,America/Chicago,NaN,Milton,Office,weather3.csv,1.901054,High,Group4
Office_Lane,2015-11-30 23:00:00,2014-12-01,NaN,Heat network,Education,Heat Network,8.0,NaN,Office,NaN,...,3201.000000,College/University,Europe/London,1907,Lane,Office,weather5.csv,1.925430,High,Group6
Office_Cameron,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,Office,NaN,...,4952.008609,College/University,America/New_York,1981,Cameron,Office,weather2.csv,2.166041,High,Group3
UnivLab_Lea,2015-11-30 23:00:00,2014-12-01,NaN,Gas,Education,Gas,6.0,NaN,College Laboratory,NaN,...,1561.000000,College/University,Europe/London,1995,Lea,UnivLab,weather5.csv,2.426095,High,Group6
UnivLab_Carlos,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,2800.375129,College/University,America/New_York,1951,Carlos,UnivLab,weather2.csv,2.484172,High,Group3
UnivLab_Aoife,2015-12-31 23:00:00,2015-01-01,NaN,NaN,Education,NaN,NaN,NaN,College Laboratory,NaN,...,24265.148760,College/University,America/Phoenix,NaN,Aoife,UnivLab,weather0.csv,2.516435,High,Group1

# First we make the time series input files

In [9]:
meta_tooutput = pd.DataFrame(meta.primaryspaceuse_abbrev+","+meta.usagecategory+","+meta.operationsgroup)

In [10]:
meta_tooutput

                                        0
uid
PrimClass_Everett      PrimClass,Low,Misc
UnivClass_Clifford   UnivClass,Low,Group3
Office_Elizabeth          Office,Low,Misc
Office_Ellie              Office,Low,Misc
PrimClass_Elisabeth    PrimClass,Low,Misc
Office_Cristina         Office,Low,Group3
PrimClass_Jolie      PrimClass,Low,Group2
PrimClass_Jaylin     PrimClass,Low,Group2
Office_Jesus            Office,Low,Group2
PrimClass_Esmeralda    PrimClass,Low,Misc
PrimClass_Eoghan       PrimClass,Low,Misc
PrimClass_Edwin        PrimClass,Low,Misc
PrimClass_Eli          PrimClass,Low,Misc
PrimClass_Ethel        PrimClass,Low,Misc
PrimClass_Ernesto      PrimClass,Low,Misc
PrimClass_Emanuela     PrimClass,Low,Misc
PrimClass_Emilio       PrimClass,Low,Misc
PrimClass_Eleanor      PrimClass,Low,Misc
PrimClass_Ezekiel      PrimClass,Low,Misc
PrimClass_Elliott      PrimClass,Low,Misc
PrimClass_Ellen        PrimClass,Low,Misc
PrimClass_Evie         PrimClass,Low,Misc
PrimClass_Elijah       PrimClass,Low,Misc
PrimClass_Ezra         PrimClass,Low,Misc
PrimClass_Edmund       PrimClass,Low,Misc
PrimClass_Eva          PrimClass,Low,Misc
Office_Erik               Office,Low,Misc
PrimClass_Ebony        PrimClass,Low,Misc
PrimClass_Ethan        PrimClass,Low,Misc
PrimClass_Elmer        PrimClass,Low,Misc
...                                   ...
UnivLab_Cristian      UnivLab,High,Group3
UnivLab_Carley        UnivLab,High,Group3
UnivLab_Alina         UnivLab,High,Group1
UnivLab_Allison       UnivLab,High,Group1
UnivLab_Peyton        UnivLab,High,Group5
Office_Marcia          Office,High,Group4
UnivLab_Aine          UnivLab,High,Group1
UnivLab_Santiago      UnivLab,High,Group7
UnivLab_Anita         UnivLab,High,Group1
UnivLab_Parker        UnivLab,High,Group5
UnivLab_Lee           UnivLab,High,Group6
Office_Dorian          Office,High,Group8
Office_Shelly          Office,High,Group7
UnivLab_Alisa         UnivLab,High,Group1
UnivLab_Louie         UnivLab,High,Group6
UnivLab_Priscilla     UnivLab,High,Group5
UnivLab_Patrick       UnivLab,High,Group5
UnivDorm_Adriana     UnivDorm,High,Group1
UnivLab_Carole        UnivLab,High,Group3
UnivLab_Paris         UnivLab,High,Group5
Office_Pauline         Office,High,Group5
UnivLab_Dianna        UnivLab,High,Group8
UnivDorm_Cecilia     UnivDorm,High,Group3
Office_Luann           Office,High,Group6
Office_Milton          Office,High,Group4
Office_Lane            Office,High,Group6
Office_Cameron         Office,High,Group3
UnivLab_Lea           UnivLab,High,Group6
UnivLab_Carlos        UnivLab,High,Group3
UnivLab_Aoife         UnivLab,High,Group1

[507 rows x 1 columns]

In [11]:
meta_tooutput['outputfile'] = meta_tooutput.index+".dat"

In [12]:
meta_tooutput.index = meta_tooutput.outputfile

In [13]:
meta_tooutput.head()

                                            0               outputfile
outputfile
PrimClass_Everett.dat      PrimClass,Low,Misc    PrimClass_Everett.dat
UnivClass_Clifford.dat   UnivClass,Low,Group3   UnivClass_Clifford.dat
Office_Elizabeth.dat          Office,Low,Misc     Office_Elizabeth.dat
Office_Ellie.dat              Office,Low,Misc         Office_Ellie.dat
PrimClass_Elisabeth.dat    PrimClass,Low,Misc  PrimClass_Elisabeth.dat

In [14]:
meta_tooutput = meta_tooutput[0]

In [16]:
#meta_tooutput

In [17]:
meta_tooutput.to_csv("/Users/Clayton/hctsa/TimeSeries/INP_buildinggenome.txt",sep=" ", header=False)

Make temp files

In [25]:
buildinglist = list(meta.index)

In [26]:
# for buildingname in buildinglist:
#     print buildingname
#     temp[buildingname].dropna().to_csv("/Users/Clayton/hctsa/TimeSeries/"+buildingname+".dat",header=False, index=False)

# Make files that are similar to the output files from the hctsa to create the same visualizations

In [27]:
features = pd.read_csv(os.path.join(repos_path, "data/processed/ALLFEATURES.CSV"), index_col="Unnamed: 0")

In [28]:
features.info()

<class 'pandas.core.frame.DataFrame'>
Index: 507 entries, Office_Abbey to UnivLab_Tracy
Columns: 166 entries, BG_breakouts_max: to BG_visdom_t90t
dtypes: float64(166)
memory usage: 661.5+ KB

In [29]:
features.columns

Index([u'BG_breakouts_max:', u'BG_dayfilterfreq_mean', u'BG_dayfilterfreq_std',
       u'BG_dayfilterfreq_min', u'BG_dayfilterfreq_max',
       u'BG_eemeter_cooling_mean', u'BG_eemeter_cooling_std',
       u'BG_eemeter_cooling_min', u'BG_eemeter_cooling_max',
       u'BG_eemeter_heating_mean',
       ...
       u'BG_visdom_min.hr.kw', u'BG_visdom_min.hr.tout', u'BG_visdom_mn2mx',
       u'BG_visdom_n2d', u'BG_visdom_nv2dv', u'BG_visdom_range',
       u'BG_visdom_t10kw', u'BG_visdom_t10t', u'BG_visdom_t90kw',
       u'BG_visdom_t90t'],
      dtype='object', length=166)

In [32]:
operations = features.columns

In [33]:
operations = pd.DataFrame(operations.str.replace('[^\w\s]',''))

In [34]:
operations

                                 0
0                 BG_breakouts_max
1            BG_dayfilterfreq_mean
2             BG_dayfilterfreq_std
3             BG_dayfilterfreq_min
4             BG_dayfilterfreq_max
5          BG_eemeter_cooling_mean
6           BG_eemeter_cooling_std
7           BG_eemeter_cooling_min
8           BG_eemeter_cooling_max
9          BG_eemeter_heating_mean
10          BG_eemeter_heating_std
11          BG_eemeter_heating_min
12          BG_eemeter_heating_max
13             BG_eemeter_baseload
14            BG_eemeter_heatbalpt
15            BG_eemeter_heatslope
16            BG_eemeter_coolbalpt
17            BG_eemeter_coolslope
18                 BG_eemeter_nmbe
19               BG_eemeter_cvrmse
20   BG_jmotif_inclasssim_168_6_14
21       BG_weeklyspecificity_mean
22        BG_weeklyspecificity_std
23        BG_weeklyspecificity_min
24        BG_weeklyspecificity_max
25     BG_jmotif_inclasssim_24_8_8
26      BG_weeklyspecificity_mean1
27       BG_weeklyspecificity_std1
28       BG_weeklyspecificity_min1
29       BG_weeklyspecificity_max1
..                             ...
136                 BG_visdom_kw90
137        BG_visdom_BG_visdom_max
138                BG_visdom_max97
139                BG_visdom_maxMA
140           BG_visdom_maxdaydate
141             BG_visdom_maxdaykw
142  BG_visdom_BG_visdom_maxdaypct
143           BG_visdom_maxdaytout
144            BG_visdom_maxhrdate
145              BG_visdom_maxhrkw
146            BG_visdom_maxhrtout
147               BG_visdom_maxHOD
148                 BG_visdom_mean
149                  BG_visdom_min
150                 BG_visdom_min3
151           BG_visdom_mindaydate
152             BG_visdom_mindaykw
153            BG_visdom_mindaypct
154           BG_visdom_mindaytout
155            BG_visdom_minhrdate
156              BG_visdom_minhrkw
157            BG_visdom_minhrtout
158                BG_visdom_mn2mx
159                  BG_visdom_n2d
160                BG_visdom_nv2dv
161                BG_visdom_range
162                BG_visdom_t10kw
163                 BG_visdom_t10t
164                BG_visdom_t90kw
165                 BG_visdom_t90t

[166 rows x 1 columns]

In [242]:
operations['name'] = operations[0]
#operations['keywords'] = "misc,raw,lengthdep"

In [243]:
operations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 2 columns):
0       166 non-null object
name    166 non-null object
dtypes: object(2)
memory usage: 2.7+ KB

In [244]:
operations.to_csv("/Users/Clayton/hctsa/Database/INP_allbg_ops.txt", header=False, index=False, sep=" ")

In [245]:
#operations

In [246]:
masteroperations = operations

In [247]:
masteroperations = masteroperations.reset_index()

In [248]:
masteroperations[0] = masteroperations["index"].apply(lambda x: "AllBGOperations(y,"+str(x)+")")

In [249]:
#masteroperations

In [250]:
masteroperations = masteroperations.drop(['index'],axis=1)

In [253]:
masteroperations

                          0                           name
0      AllBGOperations(y,0)               BG_breakouts_max
1      AllBGOperations(y,1)          BG_dayfilterfreq_mean
2      AllBGOperations(y,2)           BG_dayfilterfreq_std
3      AllBGOperations(y,3)           BG_dayfilterfreq_min
4      AllBGOperations(y,4)           BG_dayfilterfreq_max
5      AllBGOperations(y,5)        BG_eemeter_cooling_mean
6      AllBGOperations(y,6)         BG_eemeter_cooling_std
7      AllBGOperations(y,7)         BG_eemeter_cooling_min
8      AllBGOperations(y,8)         BG_eemeter_cooling_max
9      AllBGOperations(y,9)        BG_eemeter_heating_mean
10    AllBGOperations(y,10)         BG_eemeter_heating_std
11    AllBGOperations(y,11)         BG_eemeter_heating_min
12    AllBGOperations(y,12)         BG_eemeter_heating_max
13    AllBGOperations(y,13)            BG_eemeter_baseload
14    AllBGOperations(y,14)           BG_eemeter_heatbalpt
15    AllBGOperations(y,15)           BG_eemeter_heatslope
16    AllBGOperations(y,16)           BG_eemeter_coolbalpt
17    AllBGOperations(y,17)           BG_eemeter_coolslope
18    AllBGOperations(y,18)                BG_eemeter_nmbe
19    AllBGOperations(y,19)              BG_eemeter_cvrmse
20    AllBGOperations(y,20)  BG_jmotif_inclasssim_168_6_14
21    AllBGOperations(y,21)      BG_weeklyspecificity_mean
22    AllBGOperations(y,22)       BG_weeklyspecificity_std
23    AllBGOperations(y,23)       BG_weeklyspecificity_min
24    AllBGOperations(y,24)       BG_weeklyspecificity_max
25    AllBGOperations(y,25)    BG_jmotif_inclasssim_24_8_8
26    AllBGOperations(y,26)     BG_weeklyspecificity_mean1
27    AllBGOperations(y,27)      BG_weeklyspecificity_std1
28    AllBGOperations(y,28)      BG_weeklyspecificity_min1
29    AllBGOperations(y,29)      BG_weeklyspecificity_max1
..                      ...                            ...
136  AllBGOperations(y,136)                 BG_visdom_kw90
137  AllBGOperations(y,137)        BG_visdom_BG_visdom_max
138  AllBGOperations(y,138)                BG_visdom_max97
139  AllBGOperations(y,139)                BG_visdom_maxMA
140  AllBGOperations(y,140)           BG_visdom_maxdaydate
141  AllBGOperations(y,141)             BG_visdom_maxdaykw
142  AllBGOperations(y,142)  BG_visdom_BG_visdom_maxdaypct
143  AllBGOperations(y,143)           BG_visdom_maxdaytout
144  AllBGOperations(y,144)            BG_visdom_maxhrdate
145  AllBGOperations(y,145)              BG_visdom_maxhrkw
146  AllBGOperations(y,146)            BG_visdom_maxhrtout
147  AllBGOperations(y,147)               BG_visdom_maxHOD
148  AllBGOperations(y,148)                 BG_visdom_mean
149  AllBGOperations(y,149)                  BG_visdom_min
150  AllBGOperations(y,150)                 BG_visdom_min3
151  AllBGOperations(y,151)           BG_visdom_mindaydate
152  AllBGOperations(y,152)             BG_visdom_mindaykw
153  AllBGOperations(y,153)            BG_visdom_mindaypct
154  AllBGOperations(y,154)           BG_visdom_mindaytout
155  AllBGOperations(y,155)            BG_visdom_minhrdate
156  AllBGOperations(y,156)              BG_visdom_minhrkw
157  AllBGOperations(y,157)            BG_visdom_minhrtout
158  AllBGOperations(y,158)                BG_visdom_mn2mx
159  AllBGOperations(y,159)                  BG_visdom_n2d
160  AllBGOperations(y,160)                BG_visdom_nv2dv
161  AllBGOperations(y,161)                BG_visdom_range
162  AllBGOperations(y,162)                BG_visdom_t10kw
163  AllBGOperations(y,163)                 BG_visdom_t10t
164  AllBGOperations(y,164)                BG_visdom_t90kw
165  AllBGOperations(y,165)                 BG_visdom_t90t

[166 rows x 2 columns]

In [252]:
masteroperations.to_csv("/Users/Clayton/hctsa/Database/INP_allbg_mops.txt", header=False, index=False, sep=" ")

In [256]:
TS_Quality = pd.DataFrame(0, index=np.arange(507), columns=np.arange(166))

In [257]:
TS_Quality

,0,1,2,3,4,5,6,7,8,9,...,156,157,158,159,160,161,162,163,164,165
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
478,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
479,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
480,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
481,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
482,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
483,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
484,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
485,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
486,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
487,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
488,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
490,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
491,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
492,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
493,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
494,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
495,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
501,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
502,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
503,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
504,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
505,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
506,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [258]:
TS_Quality.to_csv("/Users/Clayton/hctsa/TS_QualityDummy.txt", header=False, index=False)